### ISSUE TITLE
Implement 64-bit stable memory APIs

### ISSUE THREAD

**Issue by dsarlis** [dfinity/ic-hs#28]
We would like to implement the new 64-bit stable memory APIs in the reference implementation so that we can also make a new release of the Interface spec and have end users start using the extended stable memory.

Looking into the code a bit I figured out that the main blocker right now is the `Memory` [module](https://github.com/dfinity-side-projects/winter/blob/e62722796e11760947a94285734e7bc29d72c389/src/Wasm/Runtime/Memory.hs) exposed by Winter which supports 32-bit memories and thus cannot be used to support the 64 bit stable memory APIs.

My idea on how this can be introduced in the least disruptive way is to provide a 64-bit Memory in Winter alongside the 32-bit one. Then the WinterMemory wrapper [module](https://github.com/dfinity/ic-hs/blob/c49a2f443d177b6486a1797ca646d8546ac7288c/src/IC/Wasm/WinterMemory.hs) can use this new 64-bit memory for either the old APIs (checking of course that the size is not bigger than allowed and casting 32 bit integers to 64 bit where necessary) or the new APIs. I think this would also be in line with future extensions of Winter (to support 64-bit wasm memories I assume you'd need a 64 bit memory implementation).

If the above sounds like a reasonable plan on a high level, then the next question would be how to best achieve this in practice. Looking at the code, it seems that we could maybe make [MemoryInst](https://github.com/dfinity-side-projects/winter/blob/e62722796e11760947a94285734e7bc29d72c389/src/Wasm/Runtime/Memory.hs#L50-L53) generic by the size of memory and save us from some ugly code duplication. This seems the most promising approach and one that should relatively minimize the amount of changes in general.

I'm curious to see what others think and open to other ideas.

**Comment by dsarlis** [comment]
Shamelessly cc'ing @nomeata as I'm sure you'll have some thoughts on this.

**Comment by nomeata** [comment]
We don’t really have to use the Winter memory here; we don't need most of the features it provides (which mostly correspond to Wasm memory instructions). Note that the module https://github.com/dfinity/ic-hs/blob/master/src/IC/Wasm/WinterMemory.hs, is only used for stable memory, so my suggestion would be to reimplement this module, keeping the interface (but with 64 bit parameters), and back it directly by a MVector (i.e. making it independent of Winter). Maybe rename it to `IC.Canister.StableMemory`, as it’d be mostly Winter-independent now.

**Comment by roman-kashitsyn** [comment]
I suggest we provide an API that works in exactly the same way as 32-bit API ASAP just to be able to run moderately-sized canisters, it doesn't need to be perfect.
I don't think anyone would want to allocate gigabytes of memory in an emulator anyway.

The next step might be making the implementation more faithful by changing the stable memory representation (something `IntMap (ST s (MutableWasmPage s))` looks promising).

**Comment by nomeata** [comment]
Isn’t the primary purpose of `ic-ref` to be a reference implementation? So I think it’s important that it behaves as spec’ed there. 

And unless the performance is really too bad, I would shy away from fancy implementations motivated by what the replica does. I envision `ic-ref` staying close to the Interface Spec, not the replica implementation.

**Comment by roman-kashitsyn** [comment]
Ok, I don't have strong preferences, I'm just not sure we'll be able to test big memories using a naive implementation.

I changed #34 along those lines:

>  my suggestion would be to reimplement this module, keeping the interface (but with 64 bit parameters), and back it directly by a MVector (i.e. making it independent of Winter). Maybe rename it to IC.Canister.StableMemory, as it’d be mostly Winter-independent now.

Though I used unboxed byte arrays from `primitive` package directly.

**Comment by roman-kashitsyn** [comment]
@nomeata, how do you feel about representing stable memory as a list of writes? Something like
```
data StableMemory = { smSize: Size, smModifications: [(Address, ByteString)] }
```
The reads become: 
* Allocate a buffer of the right size filled with zeros
* Iterate over modifications backwards and copy overlaps into the buffer.

The rest of the operations become trivial. This representation handles arbitrary big memories and IMO much simpler than the ByteBuffer mess.

**Comment by nomeata** [comment]
Interesting idea! It might be relatively slow for something like the Internet Identity, which uses the stable memory as backing storage (but the II test suite isn’t that large, so should be fine). And it’s not nice that Stable memory becomes even more different from normal memory, when the intention is to make them same eventually.

But I do like the declarative character of this. Anyways, it’s all in a nicely isolated module, and it does allow testing large sparse data. So sure, why not :)

**Comment by roman-kashitsyn** [comment]
Implemented the idea here: https://github.com/dfinity/ic-hs/pull/34/commits/156bf0d509c562d84eaa21b2fd9ae5192ac40c28
Works beautifully, ic-ref-test runtime and memory consumption plummeted.
