### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by nmattia** [dfinity/ic-hs#44]
It would be great to have standalone macOS and Linux binaries released for every version.

**Comment by nomeata** [comment]
Someone took away my admin rights from this repo, at some point, without telling me, let alone explaining this to me.

JFTR, this is demotivating, and will make it less likely that I’ll take good devops care about this (or even work on it otherwise).

Also pinging @basvandijk and @nikolay-komarevskiy.

**Comment by dominikayyildiz** [comment]
Dear @nomeata,

You have RW access to this repo. May I ask you to understand why you need admin access?

We are really sorry. I don't know yet how this happened, but there was definitely no malicious intent behind it.

Thanks in advance.

Kind regards,
Dominik

**Comment by nomeata** [comment]
For example for things like force-merging PRs like https://github.com/dfinity/ic-hs/pull/77 that need to bypass the CI restrictions.

Besides that… I’m not sure of concrete examples. I just am under the impression that I am still the main caretaker of `ic-hs` (used by this repo and by `motoko`). For example, the CI uses a cachix nix cache that’s under my account, so it seems odd to not be allowed to administrate the repository.

Speaking of cachix, I wonder if we should stop being cheap and actually pay them for our use of their services, at least the basic account of <https://app.cachix.org/organization/ic/billing>. I already run the cache under a “internet computer” org there separate from my personal account, so it should be possible to add someone from DFINITY as a backup owner, and start paying them a bit.

**Comment by nomeata** [comment]
Anyways, I calmed down again :-)

Maybe it's for the better this way, I always get schiefe Blicke for still working on IC stuff, right @crusso ;-)?

**Comment by nmattia** [comment]
@nomeata it looks like you're admin now; maybe @dominikayyildiz worked his magic?

**Comment by nomeata** [comment]
Yes! Thanks :-)

**Comment by mraszyk** [comment]
@nmattia Does #111 solve this issue?

**Comment by nmattia** [comment]
@mraszyk we've moved away from this actually, so all problems solved! Thanks for the follow up though
