### ISSUE TITLE
Provide x86_64-darwin builds again since dfinity/sdk depends on it

### ISSUE THREAD

**Issue by basvandijk** [dfinity/ic-hs#84]
The DFINITY SDK team has notified us that they rely on `ic-hs` in their tests. In order for them to make a release for x86_64-darwin they need a build of `ic-us` for that platform.

We recently removed support for x86_64-darwin (https://github.com/dfinity/ic-hs/pull/81) because we switched to building remotely on nixbuild.net which doesn't support that platform (yet). The reason we switched was the high-memory usage in building https://github.com/dfinity/ic-hs/pull/79 which required more memory (~ 18.2 GB) than what's available on GitHub runners (7 GB).

So in order to support x86_64-darwin again we need to:

* Enable x86_64-darwin builds again. For that platform we just build locally on GitHub runners.

* Fix the high-memory usage. Some things we can do/try:
  * Split up `IC.Test.Agent` and `IC.Test.Spec` since compiling those modules requires massive RAM.
  * Switch to a more recent GHC with the hope that it fixes the memory issue. GHC-9.2 in particular as made improvements there. See: https://well-typed.com/blog/2021/03/memory-return/
    To switch we probably need to upgrade to nixpkgs-22.05 (which we're doing in https://github.com/dfinity/ic-hs/pull/76).
  * Ideally we gain an understanding of why GHC suddenly requires so much memory to build `IC.Test.Agent`. [Space profiling](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/profiling.html#profiling-memory-usage) GHC could provide an answer here.

**Comment by nomeata** [comment]
The code in src/IC/Serialise.hs is probably also pretty high on memory usage, and I think we can just remove it. I built this because Hans said it would be useful if `ic-ref`, when used as an emulator on a developer machine, could persist its state. But I am not sure if anyone ever uses that feature, or if the SDK team still cares.

So maybe we can get a quick nod from the SDK team that they don't care about this feature and we can drop that code.

**Comment by nomeata** [comment]
We can probably also try passing `-M6GB` to GHC and make it not use more than 6GB, at the cost of more GC.

**Comment by basvandijk** [comment]
Thanks for those tips.

Note that I was able to get MacOS builds working again by splitting up modules in https://github.com/dfinity/ic-hs/pull/79.

Compiling the [`IC.Test.Agent.Calls`](https://github.com/dfinity/ic-hs/blob/de2926cac163b67c5b08476fe70d94a51b254dbd/src/IC/Test/Agent/Calls.hs) takes the most memory. My gut feeling is that most memory is consumed during type checking probably related to those `(ICManagement IO .! "...")` types. But just guessing here. I haven't actually looked into how that `.!` operators works.

**Comment by nomeata** [comment]
That’s from `row-types` and yes, not unlikely to be a source for long compile times. It might be worth checking with `ghc -v` if it is really the type checker (and thus the type-level computation) that is slow, or if it is producing Core that takes a long time to compiler. In the latter case, we can probably pass some flags to ghc to disable optimizations.

**Comment by nomeata** [comment]
Using 
```
{-# OPTIONS_GHC -v #-}
```
in `IC.Test.Agent`, before your split, I get these:
```
!!! Parser [IC.Test.Agent]: finished in 6.22 milliseconds, allocated 25.785 megabytes
!!! Renamer/typechecker [IC.Test.Agent]: finished in 5249.79 milliseconds, allocated 5916.571 megabytes
!!! Desugar [IC.Test.Agent]: finished in 3087.71 milliseconds, allocated 2300.284 megabytes
!!! Simplifier [IC.Test.Agent]: finished in 5682.78 milliseconds, allocated 3302.102 megabytes
!!! Specialise [IC.Test.Agent]: finished in 688.81 milliseconds, allocated 586.708 megabytes
!!! Float out(FOS {Lam = Just 0,
                   Consts = True,
                   OverSatApps = False}) [IC.Test.Agent]: finished in 550.52 milliseconds, allocated 552.749 megabytes
!!! Simplifier [IC.Test.Agent]: finished in 7318.19 milliseconds, allocated 7568.074 megabytes
!!! Simplifier [IC.Test.Agent]: finished in 5670.30 milliseconds, allocated 4212.926 megabytes
!!! Simplifier [IC.Test.Agent]: finished in 6194.52 milliseconds, allocated 4233.915 megabytes
!!! Float inwards [IC.Test.Agent]: finished in 134.16 milliseconds, allocated 67.531 megabytes
!!! Called arity analysis [IC.Test.Agent]: finished in 160.91 milliseconds, allocated 150.161 !!! Simplifier [IC.Test.Agent]: finished in 4755.34 milliseconds, allocated 4228.430 megabytes
!!! Demand analysis [IC.Test.Agent]: finished in 322.97 milliseconds, allocated 270.175 megabytes
!!! Worker Wrapper binds [IC.Test.Agent]: finished in 124.47 milliseconds, allocated 13.333 megabytes
!!! Simplifier [IC.Test.Agent]: finished in 2854.87 milliseconds, allocated 2779.259 megabytes
!!! Exitification transformation [IC.Test.Agent]: finished in 74.67 milliseconds, allocated !!! Float out(FOS {Lam = Just 0,
                   Consts = True,
                   OverSatApps = True}) [IC.Test.Agent]: finished in 3066.05 milliseconds, allocated 546.559 megabytes
!!! Common sub-expression [IC.Test.Agent]: finished in 175.64 milliseconds, allocated 354.102 megabytes
!!! Float inwards [IC.Test.Agent]: finished in 73.19 milliseconds, allocated 48.195 megabytes
!!! Simplifier [IC.Test.Agent]: finished in 2700.71 milliseconds, allocated 2269.872 megabytes
!!! Demand analysis [IC.Test.Agent]: finished in 307.62 milliseconds, allocated 186.101 megabytes
!!! CoreTidy [IC.Test.Agent]: finished in 446.43 milliseconds, allocated 391.803 megabytes
!!! CorePrep [IC.Test.Agent]: finished in 851.34 milliseconds, allocated 71.803 megabytes
!!! systool:as: finished in 0.53 milliseconds, allocated 0.177 megabytes
!!! CorePrep [IC.Test.Agent]: finished in 123.07 milliseconds, allocated 71.648 megabytes
!!! CodeGen [IC.Test.Agent]: finished in 745.81 milliseconds, allocated 1674.295 megabytes
```
which doesn’t relaly point to something obvious. There are a hell lot of coercions, which is likely due to the type level computations:

```
Result size of Desugar (after optimization)
  = {terms: 16,839,
     types: 202,918,
     coercions: 8,375,593,
     joins: 4/1,764}
```

🤷🏻

**Comment by basvandijk** [comment]
Thanks for that analysis!

On first glance, those "finished in n milliseconds" don't seem to sum up to the total time it takes to compile that module. I'll also run the above and do some more analysis when I get some time.

But since https://github.com/dfinity/ic-hs/pull/79 we have MacOS builds of ic-ref-dist again. So closing this issue.

**Comment by basvandijk** [comment]
Also note that [upgrading from GHC-8.10.7 to GHC-9.0.2](https://github.com/dfinity/ic-hs/pull/76) more than halved memory usage from  > 12 GB to < 6 GB.
